- name: Génération du CA
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - include_role:
        name: certs
        tasks_from: gen-root-cert.yml

- name: Génération du certificat des certificats host
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Certificat du service
      include_role:
        name: certs
        tasks_from: gen-host-cert.yml
      vars:
        host_name: "{{ public_host_name }}"
    - name: Certificat API DNS
      include_role:
        name: certs
        tasks_from: gen-host-cert.yml
      vars:
        host_name: "{{ dns_api_host_name }}"
    - name: Certificat PDNS admin
      include_role:
        name: certs
        tasks_from: gen-host-cert.yml
      vars:
        host_name: "{{ dns_admin_host_name }}"
    - name: Certificat grafana
      include_role:
        name: certs
        tasks_from: gen-host-cert.yml
      vars:
        host_name: "{{ grafana_host_name }}"

- name: Génération des certificats privés pour le mTLS
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: "Création du certificat pour le reverse proxy"
      include_role:
        name: certs
        tasks_from: gen-host-cert.yml
      vars:
        host_name: "{{ private_proxy_host_name }}"
    - name: "Création du certificat pour le service"
      include_role:
        name: certs
        tasks_from: gen-host-cert.yml
      vars:
        host_name: "{{ private_service_host_name }}"

- name: Déploiement
  hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - deploy
